// File generated by FlutterFire CLI.
// This is a template - you need to run 'flutterfire configure' to generate the actual file
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'This app is configured for web only. Mobile platforms are not supported.',
    );
  }

  // TODO: Replace these with your actual Firebase configuration
  // Run: dart pub global activate flutterfire_cli
  // Then: flutterfire configure --platforms=web
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
  );
}

